# Generated by Django 6.0.3 on 2026-04-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Borrowed', 'Borrowed')], default='Available', max_length=20),
        ),
    ]
