# Generated by Django 6.0.3 on 2026-04-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomschedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
    ]
