# Generated by Django 6.0.3 on 2026-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_meetingroomschedule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='in_use_by',
            new_name='current_user',
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Requested', 'Requested'), ('In Use', 'In Use')], default='Available', max_length=20),
        ),
    ]
