# Generated by Django 6.0.3 on 2026-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_in_use_by_computer_current_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='final_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Borrowed', 'Borrowed'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
    ]
