# Generated by Django 6.0.3 on 2026-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
