# Generated by Django 6.0.3 on 2026-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_enrolledstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='enrollment_year',
            field=models.IntegerField(default=2026),
        ),
    ]
