# Generated by Django 6.0.3 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_enrolledstudent_enrollment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='enrollment_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred'), ('Graduated', 'Graduated')], default='Enrolled', max_length=20),
        ),
    ]
